### ISSUE TITLE
Upstream merge

### ISSUE THREAD

**Issue by craig** [LTD-Beget/tcpsecrets#7]
Hello, this is great work!
Did you try getting it merged in mainline, so patching the kernel is not neccessary anymore?

**Comment by nradchenko** [comment]
We didn't, because the module is intended to work as a hacky part of our syncookied DDoS protection system which is a kind of specialized software, so it's much easier to distribute tcpsecrets as an addon.

Also kernel patching is not needed - most Linux distributions have their kernels already built with options listed in readme enabled.
